server:
  port: 8011

#本地环境
spring:
  application:
    name: consul
  datasource:
    url: jdbc:mysql://localhost:3306/athc_blog?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  redis:
    host: localhost
    port: 6379

auth-server: http://localhost:8010 # 认证服务器地址
security:
  oauth2:
    client:
      client-id: user
      client-secret: 123456
      scope: read
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
    resource:
      token-info-uri: ${auth-server}/oauth/check_token
      user-info-uri: ${auth-server}/user

swagger:
  exclude-path: /error, /ops/**
  authorization:
    key-name: Authorization
