server:
  port: 8011


cloud:
   consul:
      host: 39.107.106.56
      port: 8500
config:
  discovery:
    enabled: true
    serviceId: client-server


#本地环境
spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://ip:3306/cheap_car?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: pwd
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect